"""Provider endpoints verified against official documentation (2026-10-08).

Models are examples, not availability promises; users select their account's model IDs.
"""

from __future__ import annotations

from typing import Any


def _preset(
    name: str,
    label: str,
    url: str,
    docs: str,
    example: str = "",
    *,
    protocol: str = "openai",
    auth: str = "bearer",
    note: str = "",
    send_temperature: bool = True,
    max_tokens_field: str = "max_tokens",
) -> dict[str, Any]:
    return {
        "id": name,
        "label": label,
        "docs": docs,
        "model_example": example,
        "note": note,
        "config": {
            "base_url": url,
            "protocol": protocol,
            "auth_mode": auth,
            "send_temperature": send_temperature,
            "max_tokens_field": max_tokens_field,
        },
    }


PROVIDER_PRESETS = [
    _preset(
        "deepseek",
        "DeepSeek",
        "https://api.deepseek.com",
        "https://api-docs.deepseek.com/",
        "deepseek-flash",
    ),
    _preset(
        "qwen",
        "通义千问 / 阿里云百炼",
        "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope",
        "qwen-plus",
        note="中国内地端点；国际站或其他地域请替换地址。",
    ),
    _preset(
        "zhipu",
        "智谱 GLM",
        "https://open.bigmodel.cn/api/paas/v4",
        "https://docs.bigmodel.cn/cn/guide/develop/openai/introduction",
        "glm-4-flash",
    ),
    _preset(
        "openai",
        "OpenAI",
        "https://api.openai.com/v1",
        "https://developers.openai.com/api/reference/resources/chat/subresources/completions/methods/create",
        "gpt-4.1",
        send_temperature=False,
        max_tokens_field="max_completion_tokens",
        note="使用 Chat Completions；推理模型默认不发送 temperature。",
    ),
    _preset(
        "anthropic",
        "Anthropic / Claude",
        "https://api.anthropic.com/v1",
        "https://platform.claude.com/docs/en/api/messages/create",
        "claude-sonnet-4-6",
        protocol="anthropic",
        auth="api-key",
        send_temperature=False,
        note="原生 Messages 接口；嵌入模型需选择其他供应商。",
    ),
    _preset(
        "gemini",
        "Google Gemini",
        "https://generativelanguage.googleapis.com/v1beta/openai",
        "https://ai.google.dev/gemini-api/docs/openai",
        "gemini-2.5-flash",
        note="使用 Gemini 的 OpenAI 兼容层。",
    ),
    _preset(
        "azure",
        "Azure OpenAI",
        "",
        "https://learn.microsoft.com/en-us/rest/api/microsoft-foundry/azureopenai/chat",
        note="填写 https://你的资源.openai.azure.com/openai/v1；模型名填写部署名称。",
        auth="api-key",
        send_temperature=False,
        max_tokens_field="max_completion_tokens",
    ),
    _preset(
        "moonshot",
        "月之暗面 / Kimi",
        "https://api.moonshot.cn/v1",
        "https://platform.moonshot.cn/docs/guide/use-kimi-api",
        "kimi-k2.5",
        send_temperature=False,
    ),
    _preset(
        "minimax",
        "MiniMax",
        "https://api.minimax.io/v1",
        "https://platform.minimax.io/docs/api-reference/text-openai-api",
        "MiniMax-M2.5",
        note="国际站地址；国内账号可改为 https://api.minimaxi.com/v1。",
    ),
    _preset(
        "doubao",
        "豆包 / 火山方舟",
        "https://ark.cn-beijing.volces.com/api/v3",
        "https://docs.volcengine.com/docs/ark/quick-start?lang=zh",
        note="填写控制台中的模型 ID 或推理接入点 ID；不同地域请更换端点。",
    ),
    _preset(
        "hunyuan",
        "腾讯混元",
        "https://api.hunyuan.cloud.tencent.com/v1",
        "https://cloud.tencent.cn/document/product/1729/111007",
        "hunyuan-turbos-latest",
    ),
    _preset(
        "baidu",
        "百度千帆 / 文心",
        "https://qianfan.baidubce.com/v2",
        "https://cloud.baidu.com/doc/qianfan-docs/s/Fm9l6ocai",
        note="使用千帆 V2 API Key，填写已开通的模型名称。",
    ),
    _preset(
        "siliconflow",
        "硅基流动",
        "https://api.siliconflow.cn/v1",
        "https://docs.siliconflow.cn/docs/userguide/quickstart",
        "Qwen/Qwen3-8B",
    ),
    _preset(
        "openrouter",
        "OpenRouter",
        "https://openrouter.ai/api/v1",
        "https://openrouter.ai/docs/quickstart",
        "openai/gpt-4.1",
    ),
    _preset(
        "groq",
        "Groq",
        "https://api.groq.com/openai/v1",
        "https://console.groq.com/docs/openai",
        "llama-3.3-70b-versatile",
    ),
    _preset(
        "xai",
        "xAI / Grok",
        "https://api.x.ai/v1",
        "https://docs.x.ai/developers/rest-api-reference",
        "grok-4",
        send_temperature=False,
    ),
    _preset(
        "mistral",
        "Mistral AI",
        "https://api.mistral.ai/v1",
        "https://docs.mistral.ai/api",
        "mistral-small-latest",
    ),
    _preset(
        "together",
        "Together AI",
        "https://api.together.xyz/v1",
        "https://docs.together.ai/docs/inference/openai-compatibility",
    ),
    _preset(
        "fireworks",
        "Fireworks AI",
        "https://api.fireworks.ai/inference/v1",
        "https://docs.fireworks.ai/tools-sdks/openai-compatibility",
    ),
    _preset(
        "nvidia",
        "NVIDIA NIM",
        "https://integrate.api.nvidia.com/v1",
        "https://docs.api.nvidia.com/nim/reference/llm-apis",
    ),
    _preset(
        "cohere",
        "Cohere",
        "https://api.cohere.ai/compatibility/v1",
        "https://docs.cohere.com/docs/compatibility-api",
        "command-a-plus-05-2026",
    ),
    _preset(
        "ollama",
        "Ollama（本地）",
        "http://localhost:11434/v1",
        "https://docs.ollama.com/api/openai-compatibility",
        "qwen3:8b",
        auth="none",
        note="服务地址相对于后端主机；容器内 localhost 不指向宿主机。",
    ),
    _preset(
        "bedrock",
        "Amazon Bedrock",
        "https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1",
        "https://docs.aws.amazon.com/bedrock/latest/userguide/inference-chat-completions.html",
        "openai.gpt-oss-120b-1:0",
        send_temperature=False,
        note="使用 Bedrock API Key；请按模型所在地域更换地址，不支持此处配置 AWS SigV4 凭据。",
    ),
    _preset(
        "vertex",
        "Google Vertex AI",
        "",
        "https://docs.cloud.google.com/vertex-ai/generative-ai/docs/migrate/openai/auth-and-credentials",
        note="填写项目 / 地域对应的 OpenAI 兼容端点与 OAuth access token；短期 token 不会自动刷新。",
    ),
    _preset(
        "stepfun",
        "阶跃星辰 / StepFun",
        "https://api.stepfun.com/v1",
        "https://platform.stepfun.com/docs/zh/api-reference/chat/chat-completion-create",
    ),
    _preset(
        "spark",
        "讯飞星火",
        "https://spark-api-open.xf-yun.com/agent/v1",
        "https://www.xfyun.cn/doc/spark/X2-Flash.html",
        "spark-x",
        note="X2-Flash 的 OpenAI 端点，使用 API Password；其他星火版本请按文档调整地址。",
    ),
    _preset(
        "perplexity",
        "Perplexity / Sonar",
        "https://api.perplexity.ai",
        "https://docs.perplexity.ai/docs/sonar/quickstart",
        "sonar",
    ),
    _preset(
        "cerebras",
        "Cerebras",
        "https://api.cerebras.ai/v1",
        "https://inference-docs.cerebras.ai/resources/openai",
    ),
    _preset(
        "lmstudio",
        "LM Studio（本地）",
        "http://localhost:1234/v1",
        "https://lmstudio.ai/docs/developer/openai-compat",
        auth="none",
        note="填写本地已加载的模型 ID。",
    ),
    _preset(
        "custom",
        "自定义 OpenAI 兼容服务",
        "",
        "",
        note="可连接 vLLM、SGLang 或内部网关，填写完整 API 基址。",
    ),
]
